### ISSUE TITLE
Unnamed coordinate frames of the same type cause bounding_box error

### ISSUE THREAD

**Issue by rosteen** [spacetelescope/gwcs#398]
I'm trying to construct a very simple dummy GWCS to essentially just do an identity transform from pixel to pixel coordinates. I would have thought the code below would be sufficient, but I'm getting an error trace related to `pixel_bounds` and `bounding_box`. I thought that having `pixel_bounds` set as `None` was a common use case, so this surprised me. Would you please let me know if there's something wrong with my code below, or if this is a bug in GWCS?

```
import gwcs
from gwcs.coordinate_frames import CoordinateFrame
from astropy.modeling import models

frame1 = CoordinateFrame(2, ['SPATIAL', 'SPATIAL'], [0,1], unit=[u.pix, u.pix])
frame2frame = models.Multiply(1) & models.Multiply(1)
dummy_wcs = gwcs.WCS([(frame1, frame2frame), (frame1, None)])
```

This results in the following when trying to actually use the dummy GWCS:

```
dummy_wcs([2*u.pix, 8*u.pix])

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rosteen/opt/anaconda3/envs/viz_dev/lib/python3.9/site-packages/gwcs/wcs.py", line 363, in __call__
    if self.bounding_box is not None:
  File "/Users/rosteen/opt/anaconda3/envs/viz_dev/lib/python3.9/site-packages/gwcs/wcs.py", line 1321, in bounding_box
    bb = transform_0.bounding_box
AttributeError: 'NoneType' object has no attribute 'bounding_box'
```

**Comment by rosteen** [comment]
In the grand tradition of figuring things out after publicly asking about them, I realized that this is because both the input and output frame end up with the identical generic name "CoordinateFrame" and the GWCS machinery seems to get confused getting the transform, instead returning `None` instead of the proper transform. If I give my coordinate frames names it works, but note that it still fails if I give separate unnamed `CoordinateFrame` as the input and output frame.

```
>>> frame1 = CoordinateFrame(2, ['SPATIAL', 'SPATIAL'], [0,1], unit=[u.pix, u.pix], name = "Dummy1")
>>> frame2 = CoordinateFrame(2, ['SPATIAL', 'SPATIAL'], [0,1], unit=[u.pix, u.pix], name = "Dummy2")

>>> pipeline = gwcs.WCS([(frame1, frame2frame), (frame2, None)])
(<Quantity 1. pix>, <Quantity 8. pix>)
```

It seems like using unnamed coordinate frames shouldn't be a failure mode, or at least that the error message resulting from that case should be more informative, so I'm going leave this issue open and rename it.
